name: 'Terraform'

on:
  push:
    branches:
      - dev
      - main
    # paths:
    #   - 'infra/**'

env:
  TF_WORKSPACE: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}

    defaults:
      run:
        working-directory: ./infra

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Read AWS Region from HCL
      id: region
      run: |
        REGION=$(grep "region" backend-${{ env.TF_WORKSPACE }}.hcl | cut -d'"' -f2)
        echo "AWS_REGION=$REGION" >> $GITHUB_ENV

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7

    - name: Create Backend Resources
      uses: ./.github/actions/create-backend

    - name: Terraform Format
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init -backend-config=backend-${{ env.TF_WORKSPACE }}.hcl

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color -var-file=${{ env.TF_WORKSPACE }}.tfvars

    - name: Terraform Apply
      run: terraform apply -auto-approve -var-file=${{ env.TF_WORKSPACE }}.tfvars 